kafka:
  bootstrap:
    address: localhost:29092

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



